config/routes.rb
Rails.application.routes.draw do

  get 'application/hello'
  get 'static_pages/home'

  #---------------------------------------------------------
  # 静的ページ
  #---------------------------------------------------------
  # get 'static_pages/help'
  get '/help', to: 'static_pages#help', as: 'help'

  # get 'static_pages/about'
  get '/about', to: 'static_pages#about'

  #get 'static_pages/contact'
  # 以下の書き方をすると「_path」「_url」のlink_to指定が有効になる。
  get '/contact', to: 'static_pages#contact'


  #---------------------------------------------------------
  # ログイン関連
  #---------------------------------------------------------
  # get    'sessions/new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy' #POSTではなくDELETEであるところに注意


  #---------------------------------------------------------
  # ユーザー関連
  #---------------------------------------------------------
  # get 'users/new'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # ユーザーテーブルに基づくリソース
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root "application#hello"
  root "static_pages#home"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>

<%= link_to "Contact", contact_url %>

  <nav>
    <ul>
      <li><%= link_to "About",   about_path   %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path  %></li>
        <li><%= link_to "Help",   help_path  %></li>

        <% if(log_in?) %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to "Profile",  current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out",  logout_path, method: :delete %></li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

<body>

<%= render 'layouts/header' %>

<div class="container">
  <% #フラッシュメッセージ出力 %>
  <% flash.each do |message_type, message| %>
    <%= content_tag(
      :div,    # タグ指定
      message, # 内容指定
      class: "alert alert-#{message_type}"
    ) %>

  <% end %>

  <% #本体コンテンツ %>
  <%= yield %>

  <% #フッター %>
  <%= render 'layouts/footer' %>
</div>

<div class="container">
  <%# 開発環境であればデバッグ出力 %>
  <%= debug(params) if Rails.env.development? %>
</div>


</body>
</html>